name: Lint Charts

on:
  pull_request:
    paths:
      - 'stable/**'

  workflow_dispatch:

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run chart-testing (lint)
        uses: helm/chart-testing-action@0d28d3144d3a25ea2cc349d6e59901c4ff469b3b # v2.7.0
        with:
          command: lint
          config: .github/ct.yaml
