name: Release Helm Chart
on:
  push:
    branches:
      - main
    paths:
      - "charts/**"

  release:
    types:
      - published
      - created

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Publish Helm chart
        uses: helm/chart-releaser-action@ffaa7be82753e7c58be4ff39854a4f8b79b140de # v1.7.0
        with:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
